[theme]
primaryColor = "#4ECDC4"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1a1a2e"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

